### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by bytearchive** [neal1991/export-medium#10]
Excellent extension!!
Thanks for creating it, I can not find anything that works as well!

**Comment by setanarut** [comment]
Is it Excellent? I uninstalled the plugin after trying it.. 50% wrong parsing.

**Comment by bytearchive** [comment]
@hazarek I love it, I use it everyday. Do you have any other better recommendations?

**Comment by setanarut** [comment]
no there is no excellent converter. 
this  needs machine learning backend.
