### ISSUE TITLE
SyntaxError: Unexpected token h in JSON at position 0

### ISSUE THREAD

**Issue by filchyboy** [neal1991/export-medium#11]
The website site https://medium.com/pythonland/have-you-been-handling-python-exceptions-the-wrong-way-26dc2ad4a776 may is not supported now.
The error infomation is:SyntaxError: Unexpected token h in JSON at position 0.
It is appreciated that you can attach the error information at [issue](https://github.com/neal1991/export-medium/issues). You can click the "copy to clipboard" button to copy the information to the clipboard. Thanks.

**Comment by fspv** [comment]
Same here. Don't think this is supported anymore. The latest commit is 3 years ago.

**Comment by madneal** [comment]
The medium has disable json format response. So this extension will not work any more.

**Comment by 0xdevalias** [comment]
Potentially related:

- https://github.com/madneal/export-to-markdown/issues/9
- https://github.com/madneal/export-to-markdown/issues/12

**Comment by 0xdevalias** [comment]
@madneal I see you closed this, but I don't see any explanation / commits / etc that reference it to explain why it was closed. Can you please provide some more context.

**Comment by madneal** [comment]
why I have to explain to u? The extension wroks now. Medium enable the json API again.
