### ISSUE TITLE
Export issue

### ISSUE THREAD

**Issue by themikesirois** [neal1991/export-medium#12]
The website site https://medium.com/@manujarvinen/setting-up-a-multi-boot-of-5-linux-distributions-ca1fcf8d502 may is not supported now.
The error infomation is:SyntaxError: Unexpected token h in JSON at position 0.
It is appreciated that you can attach the error information at [issue](https://github.com/neal1991/export-medium/issues). You can click the "copy to clipboard" button to copy the information to the clipboard. Thanks.

**Comment by madneal** [comment]
sorry, the medium has disabled json format. So this plugin will not work any more.

**Comment by themikesirois** [comment]
Oh ok, No worries. Thanks for getting back to me.

**Comment by totoroot** [comment]
@madneal Thanks for creating this extension and too bad Medium now thwarted your efforts!

Please consider pinning this issue on the GitHub repository, marking the repository as archived or mentioning it at the beginning of the README as well as possibly taking the extension off the Chrome Web Store.

This will help other people avoid spending time looking for a cause for the extension not working on all Medium sites like I did.

**Comment by 0xdevalias** [comment]
Potentially related:

- https://github.com/madneal/export-to-markdown/issues/9
- https://github.com/madneal/export-to-markdown/issues/11

**Comment by 0xdevalias** [comment]
@madneal I see you closed this, but I don't see any explanation / commits / etc that reference it to explain why it was closed. Can you please provide some more context.
