### ISSUE TITLE
Chrome version  127.0.6533.89 (x86_64) the is an error 

### ISSUE THREAD

**Issue by loverasd** [neal1991/export-medium#16]
hello，the error info
The website site https://x.com/EliMiller398/with_replies may is not supported now.
The error infomation is:SyntaxError: Unexpected token 'h', "html dir=""... is not valid JSON.
It is appreciated that you can attach the error information at [issue](https://github.com/neal1991/export-medium/issues). You can click the "copy to clipboard" button to copy the information to the clipboard. Thanks.

**Comment by madneal** [comment]
does not support twitter for now
