### ISSUE TITLE
This extension doesn't support official Medium blog

### ISSUE THREAD

**Issue by jostyee** [neal1991/export-medium#2]
e.g.: https://blog.medium.com/what-are-bloom-filters-1ec2a50c68ff cannot be parsed.

**Comment by madneal** [comment]
![image](https://user-images.githubusercontent.com/12164075/31321870-460b5414-acbf-11e7-8a42-08ac7836d56b.png)
It works fine.

**Comment by jostyee** [comment]
weird..
<img width="840" alt="screen shot 2017-10-09 at 7 01 49 am" src="https://user-images.githubusercontent.com/88564/31321904-c739d7cc-acbf-11e7-80b8-4d42b72c8e1c.png">

how can I debug the extension, then?

**Comment by madneal** [comment]
just go to the developer tool in Chrome

**Comment by jostyee** [comment]
There's no option of this extension in the console dropdown list menu.
<img width="351" alt="screen shot 2017-10-09 at 10 47 20 am" src="https://user-images.githubusercontent.com/88564/31323828-5d12c186-acdf-11e7-93c2-05f3af2185a3.png">

**Comment by madneal** [comment]
it is not the place to debug, you should go to the source to debug. You should have a look at the console, to see if there is any error.
