### ISSUE TITLE
Error on fetching content from freeCodeCamp Blog

### ISSUE THREAD

**Issue by hijiangtao** [neal1991/export-medium#4]
The error shows below:

> The website site https://medium.freecodecamp.org/javascript-code-cleanup-how-you-can-refactor-to-use-classes-3948118e4468 may is not supported now.
> The error infomation is:TypeError: Cannot read property 'substring' of undefined.

**Comment by madneal** [comment]
![image](https://user-images.githubusercontent.com/12164075/43034211-04b57e68-8d0b-11e8-9c8e-1997bfa46c08.png)

**Comment by madneal** [comment]
Please ensure you update the latest version of extension. Now the version is 0.1.9.

**Comment by hijiangtao** [comment]
It's really weird, since I am using v0.1.9. I'll reinstall and try again later.

![image](https://user-images.githubusercontent.com/4990015/43036026-f52fc536-8d2b-11e8-941c-487d51684cba.png)
