### ISSUE TITLE
? in url causes error

### ISSUE THREAD

**Issue by redbar0n** [neal1991/export-medium#7]
Works:

`https://medium.com/@someuser/someblogposturl`

Does not work:

`https://medium.com/@someuser/someblogposturl?postPublishedType=repub`

``` Full error message:
The website site https://medium.com/@someuser/someblogposturl?postPublishedType=repub may is not supported now.
The error infomation is:SyntaxError: Unexpected token h in JSON at position 0.
It is appreciated that you can attach the error information at [issue](https://github.com/neal1991/export-medium/issues). You can click the "copy to clipboard" button to copy the information to the clipboard. Thanks.
```

**Comment by madneal** [comment]
It's not allowed to add other parameters.

**Comment by redbar0n** [comment]
The problem is that Medium automatically adds these parameters to the URL in certain cases.

**Comment by madneal** [comment]
I would know nothing if you don't give the specific url.

**Comment by redbar0n** [comment]
You could just add the parameter to any medium article URL, to reproduce the error, and see how the chrome add-on responds. But here is the example which made it crop up for me: 
`https://medium.com/@magne/what-did-wittgenstein-say-about-what-a-game-is-d333383cf8b4?postPublishedType=repub`
