### ISSUE TITLE
Coursera notes not able to convert

### ISSUE THREAD

**Issue by Joe-Abraham** [neal1991/export-medium#8]
The website site https://www.coursera.org/learn/machine-learning/resources/JXWWS may is not supported now.
The error infomation is:SyntaxError: Unexpected token h in JSON at position 0.
It is appreciated that you can attach the error information at [issue](https://github.com/neal1991/export-medium/issues). You can click the "copy to clipboard" button to copy the information to the clipboard. Thanks.

**Comment by madneal** [comment]
this extension does not support coursera
