### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by TrWestdoor** [neal1991/export-medium#9]
The website site https://www.dataquest.io/blog/jupyter-notebook-tips-tricks-shortcuts/ may is not supported now.
The error infomation is:SyntaxError: Unexpected token < in JSON at position 0.
It is appreciated that you can attach the error information at [issue](https://github.com/neal1991/export-medium/issues). You can click the "copy to clipboard" button to copy the information to the clipboard. Thanks.

**Comment by 0xdevalias** [comment]
Potentially related:

- https://github.com/madneal/export-to-markdown/issues/11
- https://github.com/madneal/export-to-markdown/issues/12

**Comment by 0xdevalias** [comment]
> The medium has disable json format response. So this extension will not work any more.
> 
> _Originally posted by @madneal in https://github.com/madneal/export-to-markdown/issues/11#issuecomment-952737778_

**Comment by 0xdevalias** [comment]
@madneal I see you closed this, but I don't see any explanation / commits / etc that reference it to explain why it was closed. Can you please provide some more context.
